Product_Wishlist/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.loginreg.urls', namespace = 'login')),
    url(r'^wishlist/', include('apps.wishlist.urls', namespace = 'wishlist')),
]

apps/loginreg/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.index, name= 'index'),
    url(r'^register', views.register, name= 'register'),
    url(r'^login', views.login, name='login'),
    url(r'^success', views.success, name='success'),
	url(r'^logout', views.logout, name='logout')
	]

apps/wishlist/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^addproduct$', views.addproduct, name = 'addproduct'),
    url(r'^add_wishlist$', views.add_wishlist, name = 'add_wishlist'),
    url(r'^delete/(?P<id>\d+)/$', views.delete, name = 'delete'),
    url(r'^remove/(?P<id>\d+)/$', views.remove, name = 'remove'),
    url(r'^show/(?P<id>\d+)/$', views.show, name = 'show'),
    # url(r'^join$', views.remove, name = 'join'),
]

apps/loginreg/models.py
from __future__ import unicode_literals
import re, bcrypt
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
import datetime

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')

class UserManager(models.Manager):
    # Create list of errors to be used for validation, initialize as empty list
    def validation_errors(self, request):
        errors = []
        # Check length of first and last names
        if len(request.POST['first_name']) < 2 or len(request.POST['last_name']) < 2:
            errors.append("First and last name must be longer than two characters.")
        # Check that the email is in the correct format
        if not EMAIL_REGEX.match(request.POST['email']):
            errors.append("Must use valid email")
        # Check that password length is long enough, and matches the confirm password
        if len(request.POST['password']) < 8 or request.POST['password'] != request.POST['pwconfirm']:
            errors.append("Passwords must match and be at least 8 characters")
        # Return the list of errors in a list, to be displayed on the main page
        return errors

    def reg_validation(self, request):
        # Refer back to the validation_error function
        errors = self.validation_errors(request)
        # If there are any errors, return those errors instead of moving on
        if len(errors) > 0:
            return (False, errors)
        # If there are no errors, hash the password using Bcrypt, then add user to database
        pw_hash = bcrypt.hashpw(request.POST['password'].encode(), bcrypt.gensalt())
        user = self.create(first_name=request.POST['first_name'], last_name=request.POST['last_name'], email=request.POST['email'], pw_hash=pw_hash)
        return (True, user)

    def login_validation(self, request):
        # Check if user email and password are in database, and if they match
        try:
            user = User.objects.get(email=request.POST['email'])
            password = request.POST['password'].encode()
            if bcrypt.hashpw(password, user.pw_hash.encode()) == user.pw_hash:
                return (True, user)
        # If neither exist, just return false automatically. If one of these returns false, return the same result to keep confidentiality
        except ObjectDoesNotExist:
            pass
        return (False, ["Email/password don't match those in the database"])

class User(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.CharField(max_length=60)
    pw_hash = models.CharField(max_length=255)
    date_hire = models.DateField(default=datetime.date.today)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

apps/wishlist/models.py
from __future__ import unicode_literals
from ..loginreg.models import User
from django.db import models

# Create your models here.
class ProductManager(models.Manager):
    def validateproduct(self, data, user_id):
        errors = []
        if len(data["addedproduct"]) < 2:
            errors.append("Please enter a product for your wishlist")
            return(False, errors)
        else:
            Product.objects.create(users=User.objects.get(id=user_id), productname=data["addedproduct"])
            return(True, data)


class Product(models.Model):
    productname = models.CharField(max_length = 30)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    wishlist_item = models.ManyToManyField(User, related_name = "ManyUsers")
    users = models.ForeignKey(User)
    objects = ProductManager()

apps/loginreg/views.py
from django.shortcuts import render, redirect, HttpResponse
from .models import User
from django.contrib import messages

def index(request):
    return render(request, 'loginreg/index.html')

def register(request):
    # Return the resulting errors back from models as a stored variable
    result = User.objects.reg_validation(request)
    # If there are errors, display the error messages after redirecting to the main page
    if result[0] == False:
        print_messages(request, result[1])
        return redirect('/')
    # Otherwise, if there are no errors, sent the registered info to the login_success function
    return login_success(request, result[1])

def login(request):
    # Return the resulting errors back from models as a stored variable
    result = User.objects.login_validation(request)
    # If there are errors, display the error messages after redirecting to the main page
    if result[0] == False:
        print_messages(request, result[1])
        return redirect('/')
    # Otherwise, if there are no errors, sent the registered info to the login_success function
    return login_success(request, result[1])

def login_success(request, user):
    # Store all the login information of the logged-in user in session, then redirect them to the success page
    request.session['user'] = {
        'id' : user.id,
        'first_name' : user.first_name,
        'last_name' : user.last_name,
        'email' : user.email,
    }
    return redirect ('wishlist:index')

def print_messages(request, message_list):
    # For any error messages, add them to the error message list to be displayed on the HTML pages
    for message in message_list:
        messages.add_message(request, messages.INFO, message)

def success(request):
    # Check if the current user is in session. If not, redirect to the main page
    if not 'user' in request.session:
        return redirect('/')
    # Otherwise, send them to the success page
    return render(request, 'loginreg/success.html')

def logout(request):
    # Knock the current user out of session
    request.session.clear
    return redirect('/')

apps/wishlist/views.py
from django.shortcuts import render, redirect
from . models import Product, User
from django.contrib import messages
# from django.core.urlresolvers import reverse
# Create your views here.
def index(request):
    context = {
        'myproducts' : Product.objects.filter(users=User.objects.get(id=request.session['user']['id'])),
        'newproducts' : Product.objects.filter(wishlist_item=User.objects.filter(id=request.session['user']['id'])),
        "totalproducts" : Product.objects.exclude(users=User.objects.get(id=request.session['user']['id'])).exclude(wishlist_item=User.objects.filter(id=request.session['user']['id']))
    }
    return render(request, 'wishlist/index.html', context)

def addproduct(request):
    return render(request, "wishlist/add.html")

def add_wishlist(request): #creating
    result = Product.objects.validateproduct(request.POST, request.session['user']['id'])
    if result[0]:
        return redirect("wishlist:index")
    elif result[0] == False:
        errors = result[1]
        for error in errors:
            messages.error(request, error)
        return redirect("wishlist:addproduct")

def delete(request, id):
    Product.objects.get(id = id).delete()
    return redirect("wishlist:index")

def remove(request, id):
    Product.objects.delete(id, request.session['user']['id'])
    return redirect("wishlist:index")

def show(request, id):
    context = {
        "products": Product.objects.get(id=id)
    }
    return render(request, "wishlist/show.html", context)


def join(request, id):
    wishlist = Product.objects.get(id=id)
    user = User.objects.join(id, request.session['user']['id'])
    wishlist.ManyUsers.add(user)
    return redirect("wishlist:index")

apps/loginreg/templates/loginreg/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.css"> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">
    <title>Login and Registration</title>

    <style>

        #register{
            display: inline-block;
        }
        #login{
            display: inline-block;
            vertical-align: top;
            margin-left: 100px;
        }
    </style>
</head>
<body>
    <div id="register">
        <h2>Registration</h2>
        <form action="/register" method='post'>
            {% csrf_token %}
            <label>First Name:</label>
            <input type="text" name='first_name'><br>
            <label>Last Name:</label>
            <input type="text" name='last_name'><br>
            <label>Email:</label>
            <input type="text" name='email'><br>
            <label>Password:</label>
            <input type="password" name='password'><br>
            <label>Confirm Password:</label>
            <input type="password" name='pwconfirm'><br>
            <label>Date Hired:</label>
            <input type="date" name="date_hire">
            <input type="submit" class='pagebutton' value='Register'>
        </form>
    </div>
    <div id="login">
            <h2>Login</h2>
            <form action="login" method='post'>
                {% csrf_token %}
                <label>Email:</label>
                <input type="text" name='email'><br>
                <label>Password:</label>
                <input type="password" name='password'><br>
                <input type="submit" class='pagebutton' value='Login'>
            </form>
        {% if messages %}
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        {% endif %}
    </div>
</body>
</html>

apps/loginreg/templates/loginreg/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">
    <!-- <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.css"> -->
    <title>Success Page</title>
</head>
<body>
    <div>

        <h1>Great Success!</h1>
        <p>You did it! You totally logged in, {{request.session.user.first_name}}.</p>
        <form action="/logout">
            <input type="submit" value='Log Out'>
        </form>
    </div>
</body>
</html>

apps/wishlist/templates/wishlist/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">
    <title>Add To Wishlist</title>
</head>
<body>
    <h2>Create a New Wish List Item</h2>
    <a href="{% url 'wishlist:index' %}">Home</a> | <a href="{% url 'login:logout' %}">Logout</a>
    <hr>
    <br>
    <form class="" action="{% url 'wishlist:add_wishlist' %}" method="post">
        {% csrf_token %}
        <label>Item/Product:</label>
        <input type="text" name="addedproduct" placeholder="Add New Wishlist Item Here">
        <input type="submit" value="Add To Wishlist">
    </form>
</body>
</html>

apps/wishlist/templates/wishlist/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">
    <title>Wishlist</title>
</head>
<body>
    <h2>Hello {{request.session.user.first_name}}!</h2>
    <a href="{% url 'login:logout' %}">Logout</a>
    <hr>
    <h3>Your Wish List:</h3>
    <table>
        <thead>
            <tr>
                <th>Item</th>
                <th>Added By</th>
                <th>Date Added</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for product in myproducts %}
            <tr>
                <td><a href="{% url 'wishlist:show' product.id %}">{{product.productname}}</a></td>
                <td>{{product.users.first_name}}</td>
                <td>{{product.created_at}}</td>
                <td><a href="{% url 'wishlist:delete' product.id %}">Delete</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <h3>Other Users' Wish List:</h3>
    <table>
        <thead>
            <tr>
                <th>Item</th>
                <th>Added By</th>
                <th>Date Added</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for product in totalproducts %}
            <tr>
                <td><a href="{% url 'wishlist:show' product.id %}">{{product.productname}}</a></td>
                <td>{{product.users.first_name}}</td>
                <td>{{product.created_at}}</td>
                <td><a href="#">Add to Wishlist</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="addproduct">Add Item</a>
</body>
</html>

apps/wishlist/templates/wishlist/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">
    <title>Information</title>
</head>
<body>
    <h1>{{products.productname}} </h1>
    <a href="{% url 'wishlist:index' %}">Home</a> | <a href="{% url 'login:logout' %}">Logout</a>
    <hr>
    <br>
    <h5>Users who added this product/item under their wishlist:</h5>
    {% for users in products.join.all %}
        {{product.users}}
    {% endfor %}
</body>
</html>